In [2]:
import pandas as pd 
import numpy as np
import seaborn as sns

In [3]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df['tip_pct'] = df['tip']/df['total_bill']
df.head()

   total_bill   tip     sex smoker  day    time  size   tip_pct
0       16.99  1.01  Female     No  Sun  Dinner     2  0.059447
1       10.34  1.66    Male     No  Sun  Dinner     3  0.160542
2       21.01  3.50    Male     No  Sun  Dinner     3  0.166587
3       23.68  3.31    Male     No  Sun  Dinner     2  0.139780
4       24.59  3.61  Female     No  Sun  Dinner     4  0.146808

In [8]:
grouped = df.groupby(['day','smoker'])
grouped_pct = grouped['tip_pct']
grouped_pct.agg('mean')

day   smoker
Thur  Yes       0.163863
      No        0.160298
Fri   Yes       0.174783
      No        0.151650
Sat   Yes       0.147906
      No        0.158048
Sun   Yes       0.187250
      No        0.160113
Name: tip_pct, dtype: float64

In [10]:
functions = ['count', 'mean', 'max']
result = grouped[['tip_pct', 'total_bill']].agg(functions)
result

            tip_pct                     total_bill
              count      mean       max      count       mean    max
day  smoker
Thur Yes         17  0.163863  0.241255         17  19.190588  43.11
     No          45  0.160298  0.266312         45  17.113111  41.19
Fri  Yes         15  0.174783  0.263480         15  16.813333  40.17
     No           4  0.151650  0.187735          4  18.420000  22.75
Sat  Yes         42  0.147906  0.325733         42  21.276667  50.81
     No          45  0.158048  0.291990         45  19.661778  48.33
Sun  Yes         19  0.187250  0.710345         19  24.120000  45.35
     No          57  0.160113  0.252672         57  20.506667  48.17

In [16]:
frame = pd.DataFrame({'data1': np.random.standard_normal(1000), 
                      'data2': np.random.standard_normal(1000)})
frame

        data1     data2
0    0.719970  1.063451
1   -0.380304  1.860515
2    0.457921  0.906202
3   -0.490755  0.729991
4    0.437491  1.934638
..        ...       ...
995  4.976573 -0.749792
996  0.834325 -0.978390
997  1.417001  0.367346
998  2.992644 -0.392193
999 -1.080476  1.286848

[1000 rows x 2 columns]

In [17]:
quartiles = pd.cut(frame['data1'],4)
quartiles

0       (0.595, 2.786]
1      (-1.596, 0.595]
2      (-1.596, 0.595]
3      (-1.596, 0.595]
4      (-1.596, 0.595]
            ...
995     (2.786, 4.977]
996     (0.595, 2.786]
997     (0.595, 2.786]
998     (2.786, 4.977]
999    (-1.596, 0.595]
Name: data1, Length: 1000, dtype: category
Categories (4, interval[float64, right]): [(-3.796, -1.596] < (-1.596, 0.595] < (0.595, 2.786] < (2.786, 4.977]]

In [19]:
def get_stats(group):
    return pd.DataFrame(
        {"min": group.min(), "max": group.max(),
        "count": group.count(), "mean": group.mean()})


grouped = frame.groupby(quartiles)
grouped.apply(get_stats)

                             min       max  count      mean
data1
(-3.796, -1.596] data1 -3.787364 -1.616604     60 -2.003705
                 data2 -1.741681  2.087591     60  0.064413
(-1.596, 0.595]  data1 -1.592964  0.594048    651 -0.347929
                 data2 -3.954785  2.890419    651 -0.038745
(0.595, 2.786]   data1  0.594925  2.711434    284  1.193764
                 data2 -2.892029  2.692621    284 -0.007562
(2.786, 4.977]   data1  2.884682  4.976573      5  3.391807
                 data2 -0.901041  0.584877      5 -0.249806

In [20]:
frame.head()

      data1     data2
0  0.719970  1.063451
1 -0.380304  1.860515
2  0.457921  0.906202
3 -0.490755  0.729991
4  0.437491  1.934638

In [22]:
quartiles_samp = pd.qcut(frame["data1"], 4)
quartiles_samp

0        (0.713, 4.977]
1      (-0.725, 0.0216]
2       (0.0216, 0.713]
3      (-0.725, 0.0216]
4       (0.0216, 0.713]
             ...
995      (0.713, 4.977]
996      (0.713, 4.977]
997      (0.713, 4.977]
998      (0.713, 4.977]
999    (-3.788, -0.725]
Name: data1, Length: 1000, dtype: category
Categories (4, interval[float64, right]): [(-3.788, -0.725] < (-0.725, 0.0216] < (0.0216, 0.713] < (0.713, 4.977]]

In [23]:
s = pd.Series(np.random.standard_normal(6))
s

0   -0.323190
1   -0.096033
2    0.643226
3   -1.294334
4   -0.909533
5    0.650175
dtype: float64

In [31]:
s[::2] = np.nan
s

0         NaN
1   -0.096033
2         NaN
3   -1.294334
4         NaN
5    0.650175
dtype: float64

In [33]:
s.fillna(s.mean())

0   -0.246731
1   -0.096033
2   -0.246731
3   -1.294334
4   -0.246731
5    0.650175
dtype: float64

In [35]:
states = ["Ohio", "New York", "Vermont", "Florida", "Oregon", "Nevada", "California", "Idaho"]
group_key = ["East", "East", "East", "East", "West", "West", "West", "West"]

data = pd.Series(np.random.standard_normal(8), index=states)
data

Ohio          1.480989
New York      0.086328
Vermont      -1.281920
Florida       0.521474
Oregon        0.772613
Nevada        0.089051
California   -1.158980
Idaho         0.575579
dtype: float64

In [36]:
data[["Vermont", "Nevada", "Idaho"]] = np.nan

In [37]:
data

Ohio          1.480989
New York      0.086328
Vermont            NaN
Florida       0.521474
Oregon        0.772613
Nevada             NaN
California   -1.158980
Idaho              NaN
dtype: float64

In [38]:
def fill_mean(group):
    return group.fillna(group.mean())

In [39]:
data.groupby(group_key).apply(fill_mean)

East  Ohio          1.480989
      New York      0.086328
      Vermont       0.696264
      Florida       0.521474
West  Oregon        0.772613
      Nevada       -0.193183
      California   -1.158980
      Idaho        -0.193183
dtype: float64

In [40]:
df.head()

   total_bill   tip     sex smoker  day    time  size   tip_pct
0       16.99  1.01  Female     No  Sun  Dinner     2  0.059447
1       10.34  1.66    Male     No  Sun  Dinner     3  0.160542
2       21.01  3.50    Male     No  Sun  Dinner     3  0.166587
3       23.68  3.31    Male     No  Sun  Dinner     2  0.139780
4       24.59  3.61  Female     No  Sun  Dinner     4  0.146808

In [44]:
df.pivot_table(index=["time", "day"], columns="smoker", values=["tip_pct", "size"])

                 size             tip_pct
smoker            Yes        No       Yes        No
time   day
Lunch  Thur  2.352941  2.500000  0.163863  0.160311
       Fri   1.833333  3.000000  0.188937  0.187735
Dinner Thur       NaN  2.000000       NaN  0.159744
       Fri   2.222222  2.000000  0.165347  0.139622
       Sat   2.476190  2.555556  0.147906  0.158048
       Sun   2.578947  2.929825  0.187250  0.160113